name: pre-commit

on: [push]
# on:
#   pull_request:
#   push:
#     branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Running pre-commit
      uses: pre-commit/action@v3.0.1
